---
title: "HW5"
author: "Jianyou Liu"
date: "November 6, 2018"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))


```
## Problem 1
### Create tidy dataframe

#### Generate dataframe containing all file names

```{r}
# Create dataframe containing all 20 file names in the directory
file_df = tibble(
  list.files(path = ".//data", all.files = FALSE)) 
  
names(file_df)[1] = "file_name"

file_df
```

#### Iterate over file names and load data for each subject as nested list columns

```{r}
#  Read in observation data for each subject as list columns
combine_df = 
  file_df %>%
  mutate(file_path = paste(".//data//", file_name, sep = "")) %>% 
  mutate(data = map(.x = file_path, ~read_csv(file = .x)))

combine_df
  
```
#### Tidy resulting dataset

```{r}
# Clean data for exploratory analysis
clean_df = combine_df %>% 
  mutate(file_name = str_replace(file_name, ".csv$", "")) %>% 
  separate(file_name, into = c("arm", "subject_id"), sep = "_") %>% 
  unnest() %>% 
  gather(key = week, value = observation, week_1:week_8) %>% 
  mutate(week = str_replace(week, "^week_", ""), week = as.numeric(week)) %>% 
  select(-file_path) %>% 
  arrange(arm, subject_id)

# First 10 rows of tidy dataset
print(clean_df, 10)
  
```
#### Plot observations on each subject over time
```{r}
# Make spaghetti plot
clean_df %>% 
  ggplot(aes(x = week, y = observation, color = subject_id)) +
  geom_point(alpha = .5) + geom_line() +
  facet_grid(.~arm) +
  labs(
    title = "Comparing Observation for each Subject Over Time Between Control and Experimental Group",
    x = "Week",
    y = "Observation Units"
  )
```


